// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAQunZoDVespRl-Zg7CC49QUU7IiUM2k1E',
    appId: '1:739634769637:web:13c46ed702b1f2d64dee0c',
    messagingSenderId: '739634769637',
    projectId: 'madrasa-sofa-app-pk',
    authDomain: 'madrasa-sofa-app-pk.firebaseapp.com',
    storageBucket: 'madrasa-sofa-app-pk.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBE6iKZHXtJsRSgW5QqEqXr936Z-e4eSiI',
    appId: '1:739634769637:android:bd92f9d1f97eab144dee0c',
    messagingSenderId: '739634769637',
    projectId: 'madrasa-sofa-app-pk',
    storageBucket: 'madrasa-sofa-app-pk.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBnE_bD25K2i3peIVvHWtTo6Mpgkhg6P40',
    appId: '1:739634769637:ios:1f78a751614a25274dee0c',
    messagingSenderId: '739634769637',
    projectId: 'madrasa-sofa-app-pk',
    storageBucket: 'madrasa-sofa-app-pk.firebasestorage.app',
    iosBundleId: 'com.example.madrasaSoffa',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBnE_bD25K2i3peIVvHWtTo6Mpgkhg6P40',
    appId: '1:739634769637:ios:1f78a751614a25274dee0c',
    messagingSenderId: '739634769637',
    projectId: 'madrasa-sofa-app-pk',
    storageBucket: 'madrasa-sofa-app-pk.firebasestorage.app',
    iosBundleId: 'com.example.madrasaSoffa',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAQunZoDVespRl-Zg7CC49QUU7IiUM2k1E',
    appId: '1:739634769637:web:f93ff6a8bfe3e0244dee0c',
    messagingSenderId: '739634769637',
    projectId: 'madrasa-sofa-app-pk',
    authDomain: 'madrasa-sofa-app-pk.firebaseapp.com',
    storageBucket: 'madrasa-sofa-app-pk.firebasestorage.app',
  );
}
